services:
  frontend:
    image: zurich:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
    env_file: ../.env.local
    ports:
      - "3000:3000"
      # - "80:80"
      # - "443:443"
    environment:
      - ZURICH-CLIENT=true
    restart: always
    networks:
      - docker-zurich-client-network

networks:
  docker-zurich-client-network:
    driver: bridge